server:
  port: 8093

spring:
  application:
    name: product-microservice
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product_dev
kafka:
  bootstrapAddress: localhost:9092,localhost:9093,localhost:9094
  acks: all
  retries: 5
  retry:
    backoff:
      ms: 1000
  message:
    exchangeTopic:
      name: exchange-events
    productTopic:
      name: product_count_topic

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8092/eureka
    register-with-eureka : false
    fetch-registry: false