server:
  port: 8095
spring:
  application:
    name: order-microservice
  profiles:
    active: dev

---
spring:
  profiles: dev
  data:
    mongodb:
      host: localhost
      port: 27017
      database: order_management_db
#   username:
#   password:

kafka:
  bootstrapAddress: localhost:9092,localhost:9093,localhost:9094
  acks: all
  retries: 5
  retry:
    backoff:
      ms: 1000
  message:
    exchangeEventTopic:
      name: exchange-events
    productTopic:
      name: product_count_topic
    customerTopic:
      name: cust_credit_limit_topic

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8092/eureka
    register-with-eureka : false
    fetch-registry: false


customer:
  host:
    name: api/customers/
    url: http://localhost:8094/
    
product:
  host:
    name: api/product/
    url: http://localhost:8093/